### ISSUE TITLE
Problems chaneging suffix and prefix

### ISSUE THREAD

**Issue by bitboxer** [phrase/phraseapp-in-context-editor-ruby#1]
If I want to overwrite the prefix and suffix because I am using android,

```JS
    window.PHRASEAPP_CONFIG = {
      prefix: '[[__',
      suffix: "__]]",
    };
```

This won't work because the 

```RUBY
  = phraseapp_in_context_editor_js
```

will overwrite it with it's own hash that only contains the projectId.

Ideally the setting I am doing in the init rb script should be reflected in the auto generated hash and I should not do anything. And If I change stuff in the hash, it should be respected, not overwritten by the outputted JS snipplet.

**Comment by docstun** [comment]
Unfortunately you need to configure this in the `phraseapp_in_context_editor.js` initializer file as well since we need this information in the Ruby context:

````
PhraseApp::InContextEditor.configure do |config|
  config.prefix = "[[__"
  config.suffix = "__]]"
end
````
See the [documentation](http://docs.phraseapp.com/guides/in-context-editor/configure/) for more info.

Does this solve the problem?
