### ISSUE TITLE
Per thread config

### ISSUE THREAD

**Issue by nviennot** [phrase/phraseapp-in-context-editor-ruby#14]
The line: https://github.com/phrase/phraseapp-in-context-editor-ruby/blob/master/lib/phraseapp-in-context-editor-ruby.rb#L10 suggest that the configuration can be done per thread. However, this doesn't work as the Config class uses shared class variables: https://github.com/phrase/phraseapp-in-context-editor-ruby/blob/master/lib/phraseapp-in-context-editor-ruby/config.rb

It would be good to have a per thread configuration so we can enable/disable the editor with a before_filter in controllers. What was the original intention? Should we fix this?

**Comment by docstun** [comment]
Thanks, we'll look into this!

**Comment by docstun** [comment]
@nviennot sorry for the delay here. You're right, the current implementation is a bit confusing and comes from a very early version. However, a simple thread-only based solution might not work in a multi-thread environment. We've tested some different scenarios but did not find a great solution yet.

How would you implement it and what server are you using?

**Comment by nviennot** [comment]
The usecase is for a multithreaded webserver (e.g. puma) responding to multiple requests simultaneously. Some users/browsers have phraseapp disabled, while others have it enabled.

I would implement the following API:
- Have a global configuration like you have (`PhraseApp::InContextEditor.configure { ... }`)
- A contextual configuration: `PhraseApp::InContextEditor.with_config(:enabled => false) { code_that_run_with_the_context_aware_code }`
- When reading a configuration value, the implementation first fetches the value in the local thread setting. If not found, it returns the global setting value.

**Comment by docstun** [comment]
@nviennot thanks for the details. We've been thinking in the same direction and are working on a solution. Will let you know as soon as we have something ready.

**Comment by docstun** [comment]
@nviennot we have tackled this in the `config-current-thread` branch (https://github.com/phrase/phraseapp-in-context-editor-ruby/tree/config-current-thread).

It lets you now use the following syntax, e.g. in a controller `around_filter`:

    around_filter :handle_in_context_editor

    def handle_in_context_editor(&block)
      PhraseApp::InContextEditor.with_config(enabled: user_signed_in?) do
        yield
      end
    end

Could you take this for a test drive to see if we're on the right track?

**Comment by nviennot** [comment]
I'll come back to you tomorrow. Thanks :)

**Comment by docstun** [comment]
@nviennot did you already have a chance to look at this?

**Comment by docstun** [comment]
@nviennot any news regarding the provided solution?

**Comment by nviennot** [comment]
Argh. I'm out these days, I'll look into it by the end of the week.
I apologize for the lack of responsiveness of my end.

**Comment by docstun** [comment]
Thanks, looking forward :)

**Comment by nviennot** [comment]
Alright, I've looked at the code, and tested it. Works great!

I'm very happy about how responsive you guys are. Keep that up 👍

**Comment by docstun** [comment]
Great, you can now use the official release `1.1.0`, it includes this change.
