### ISSUE TITLE
Why Access Token is mandatory in configuration for In-Context Editor? 

### ISSUE THREAD

**Issue by jjustaments** [phrase/phraseapp-in-context-editor-ruby#2]
We need to provide user E-Mail and Password in 'PhraseApp Sign in' form when we start translating.
Translator can be another user who did not generate this access token.

**Comment by kennell** [comment]
Hi @jjustaments - the access token you provide in the configuration does not have to belong to the account signing in to the In-Context-Editor. The access token is only needed to pre-filter blacklisted keys.

So you **do not** have to create a token for the translator.

Also please note there is currently a issue that prevents Translator accounts from using the In-Context-Editor. This should be fixed within the next few hours, as a temporary workaround you can create a developer account.

**Comment by jjustaments** [comment]
Ok, thanks for the explanation.
