### ISSUE TITLE
Why PhraseApp In-Context Editor can be enabled/disabled only for entire application?

### ISSUE THREAD

**Issue by jjustaments** [phrase/phraseapp-in-context-editor-ruby#3]
It cannot be used for application in production mode because we do not need to enable PhraseApp for all application users.

**Comment by kennell** [comment]
Hi @jjustaments, not sure if i understand this correctly, but the In-Context-Editor should not be used in production mode.

**Comment by jjustaments** [comment]
We created such feature in our web app with some patch. 
Each user can turn on/off tranlsation mode only for its session.

**Comment by docstun** [comment]
@jjustaments we did experience issues in the past introduced by threading. It is not a big deal for a staging environment but we strongly advise not to use this on a production server.
