### ISSUE TITLE
Using translation in data-x attributes replaces entire string.

### ISSUE THREAD

**Issue by frederikspang** [phrase/phraseapp-in-context-editor-ruby#33]
I'm having a weird issue, that might be related to JS, and not much to the ruby-library. 

Say, for example, I have a form element with following:

     <%= f.text_area :something, :"data-validate" => "['presence','#{t('validation.required')}']" %>

The expected result is

`<textarea data-validate="['presence', 'Field is Required']"></textarea>`

Which is expected for our JS-validator to work. However, when I'm doing a JS-step-debugger (The Chrome one), with a breakpoint in the beginning of the document. (Bottom of <body>, inside our `validate.js` - After phraseapp-in-context-editor.js is loaded), I see correctly, the {{..}} string, like: (Not remembering if the text inside is correct)

`<textarea data-validate="['presence', '{{validation_required}}']"></textarea>`

When I then 'release' the breakpoint, to make it continue, it gets replaced with:

`<textarea data-validate="Field is Required"></textarea>`

It would seem, that the Phraseapp IC-Editor replaces the entire attribute, instead of only the `{{string}}` inside HTML attribute-values.

**Comment by tobstarr** [comment]
@frederikspang thank you for reporting the issue. We will look into it.

**Comment by frederikspang** [comment]
Thank you. I do, as far as I know, have a case open through regular support as well, I would much rather see changes here... As a developer ;)

**Comment by theSoenke** [comment]
Of course. I will provide the next update directly here :)

**Comment by theSoenke** [comment]
We have released an update for the InContext-Editor. Now it should no longer overwrite the complete attribute value. Maybe you can try it again whether this completely solves the issue. There should be no additional changes on your side required to test this

**Comment by frederikspang** [comment]
Hi @theSoenke 
I'll give it a go asap.

**Comment by frederikspang** [comment]
This issue seems to be fixed now. Thank you! If I find something along the same lines, I'll reopen another issue, with another reproduction-case.

**Comment by theSoenke** [comment]
Glad to hear that it solved it. And thanks for the confirmation. Let us know if you find anything else :)
