### ISSUE TITLE
Performance impact of API request per I18n key

### ISSUE THREAD

**Issue by JanStevens** [phrase/phraseapp-in-context-editor-ruby#35]
Hello

We have around 5000 translation strings in our YAML file and we noticed that the performance with the in context editor is very slow. A typical page load takes around 20-30 seconds to load. If we disable the in context editor we have again snappy pages.

After investigating I noticed that for every key we display on a page the gem makes 2 API calls (one to fetch the key meta data then to fetch all translations). For a page with around 80+ keys displayed this is a huge performance penalty. When the page does load the javascript is included and this goes and fetched the keys AGAIN but now for the in context editor.

Since this situation became unworkable for our translators we monkey patched the in context editor so it only decorates the translation keys and let the in context editor JS fill in the translations.

```ruby
module PhraseAppPerformanceImproved
  def method_missing(*args, &block)
     self.class.log "Trying to execute missing method ##{args.first} on key #{@key}"
     if @key.respond_to?(args.first)
       to_s.send(*args)
     else
       original_translation = ::I18n.translate_without_phraseapp(*@original_args)
       original_translation.send(*args, &block)
     end
  end
end

PhraseApp::InContextEditor::Delegate::I18nDelegate.prepend(PhraseAppPerformanceImproved)
```

Any reason why both server side and client side fetch translations?

**Comment by theSoenke** [comment]
Hi, could you maybe send me the log of the API request? For example [httplog](https://github.com/trusche/httplog) is very useful to get a log of the requests. That would help me a lot to debug what might cause this many requests in your case

**Comment by theSoenke** [comment]
You can also send us the logs on our [contact page](https://phraseapp.com/contact) in case you don't want to share them publicly

**Comment by JanStevens** [comment]
Sorry for the late reply, had other assignments. I've send a message through customer support, I have a 4.8M http log file. Its clear that for every key a request is made
