### ISSUE TITLE
Two translations in one HTML element

### ISSUE THREAD

**Issue by jjustaments** [phrase/phraseapp-in-context-editor-ruby#4]
The following two keys will not be translated
```
<p> {{__phrase_KEY1__}} {{__phrase_KEY2__}} </p>
```
and the result on screen will be
```
KEY1__}} {{__phrase_KEY2
```

**Comment by kennell** [comment]
I can't seem to reproduce this issue, can you give more details?

**Comment by jjustaments** [comment]
It seems that problem is with prefix and suffix.
I crated three fiddle scripts. Only one (with default prefix and suffix) works correctly.
http://jsfiddle.net/jeejee/28zcxfyp/
http://jsfiddle.net/jeejee/cpkqggbm/
http://jsfiddle.net/jeejee/btgdh7za/
<img width="729" alt="screen shot 2015-09-11 at 16 37 41" src="https://cloud.githubusercontent.com/assets/7509152/9816158/ed01c4be-58a3-11e5-8284-53345a5d8cf0.png">
<img width="827" alt="screen shot 2015-09-11 at 16 38 16" src="https://cloud.githubusercontent.com/assets/7509152/9816160/ed04ce98-58a3-11e5-8fc5-61619ebe7b31.png">
<img width="842" alt="screen shot 2015-09-11 at 16 38 50" src="https://cloud.githubusercontent.com/assets/7509152/9816159/ed041840-58a3-11e5-9eb6-85d63a12564a.png">

**Comment by kennell** [comment]
@docstun this is a issue with the In-Context-Editor JS

**Comment by docstun** [comment]
@jjustaments does the issue still occur?

**Comment by jjustaments** [comment]
Hi @docstun,

The issue is solved, thank you!
