### ISSUE TITLE
Method missing error

### ISSUE THREAD

**Issue by chrisbranson** [phrase/phraseapp-in-context-editor-ruby#5]
In some back end code we rely on I18n.t giving us a group of translations when given a parent key. This tripped an error in your method_missing method in the I18n delegate - you're calling `translate_without_phraseapp` but it's trying to do that on the delegate class rather than I18n itself (where you've aliased the old methods).

My fork fixes this with the following commit: https://github.com/insphire/phraseapp-in-context-editor-ruby/commit/10a41f1a2e95aa9599cae671238785d290ba0851

Not sure it's worth a pull request to add two colons, but I can if you'd like :smile:

**Comment by fredv** [comment]
Hey @chrisbranson, thank you for pointing this out, we will have a look at this and add it.

**Comment by kieranklaassen** [comment]
I have the same error on a `date_select` form field.

```
NoMethodError at /coupons/new
undefined method `translate_without_phraseapp' for PhraseApp::InContextEditor::Delegate::I18n:Class
```

**Comment by docstun** [comment]
We've released an update that should solve that issue: https://rubygems.org/gems/phraseapp-in-context-editor-ruby/versions/1.0.2
