### ISSUE TITLE
Outdated phraseapp-ruby dependency

### ISSUE THREAD

**Issue by ralph** [phrase/phraseapp-in-context-editor-ruby#51]
I'm working on a project that is using the in context editor, and the `phraseapp-ruby` dependency is really outdated:

https://github.com/phrase/phraseapp-in-context-editor-ruby/blob/master/phraseapp-in-context-editor-ruby.gemspec#L30

This resolves to 1.6.0, released on November 14, 2017. Can you update the in context editor lib to use a later version of the [phraseapp-ruby](https://github.com/phrase/phraseapp-ruby) gem, or switch it to the [phrase-ruby](https://github.com/phrase/phrase-ruby) lib?

**Comment by theSoenke** [comment]
Hey @ralph, it's definitely about time to update to phrase-ruby. We don't have an exact plan for when this will happen yet but I'll also bring this up internally again

**Comment by itsahsiao** [comment]
Closing this, as this dependency is no longer relevant in the latest version (v2.0.0) and the new In-Context Editor.
