### ISSUE TITLE
Introduce a changelog

### ISSUE THREAD

**Issue by nTraum** [phrase/phraseapp-in-context-editor-ruby#7]
Hi phraseapp-in-context-editor-ruby-maintainers (what a title for a business card),

What do you think about introducing a changelog users could quickly check against when updating to a newer version?

Even easier when following Semantic Versioning (http://semver.org/).

Thanks in advance!

**Comment by kieranklaassen** [comment]
This gem generates them from github: https://github.com/skywinder/github-changelog-generator

**Comment by docstun** [comment]
done. thanks @kieranklaassen for the hint.
