### ISSUE TITLE
missing gem for version v2.0.1

### ISSUE THREAD

**Issue by rocket-turtle** [phrase/phraseapp-in-context-editor-ruby#76]
There is a v2.0.1 Tag so I assumed that there is a v2.0.1 Version but there is none on the release page nor on rubygems.

https://github.com/phrase/phraseapp-in-context-editor-ruby/tree/v2.0.1

https://rubygems.org/gems/phraseapp-in-context-editor-ruby

https://github.com/phrase/phraseapp-in-context-editor-ruby/releases

**Comment by Varpusparvi** [comment]
@rocket-turtle Hey! Thanks for reporting this. We will probably not backfill the missing version but there is now the newer 2.1.1 released in `rubygems` as well as on the releases page, hopefully this helps 😄
