### ISSUE TITLE
Editor conflicts the angular router

### ISSUE THREAD

**Issue by Sysqa** [phrase/phraseapp-in-context-editor-ruby#9]
Hi,

I have an issue with the editor. I'm using angular and ngRoute module that is using `#/something`. When the editor is enabled and I try to change a language or click on my username the content disappearing and it should refresh the page to see it again.

**Comment by docstun** [comment]
I am not sure I understand you correctly. When you change the language in your app you want to update the language from the In-Context-Editor as well?

**Comment by Sysqa** [comment]
Not exactly. When I try to choose another language from the list from the In-Context-Editor the homepage content disappear I saw just a white page.

**Comment by docstun** [comment]
Did you adjust the prefix and suffix of the In-Context editor? This is important when working with AngularJS. See "Customize the key decorator": https://phraseapp.com/docs/guides/in-context-editor/configure/

**Comment by Sysqa** [comment]
Yes I did. I'm using this:
```
PhraseApp::InContextEditor.configure do |config|
  config.prefix = "{*{__"
  config.suffix = "__}*}"
end
```
This worked with the old gem.

**Comment by docstun** [comment]
It would be great if you could contact our support directly so we can dig a little deeper. Just send us an email to support@phraseapp.com
